export const WORLD = {
  MAP: 'MAP',
  TILESET_COLLIDE: 'COLLIDE',
  TILESET_1: 'TILESET_1',
  TILESET_2: 'TILESET_2',
  OBJECT_1: 'OBJECT_1',
  OBJECT_2: 'OBJECT_2',
}

export const OBJECT = {
  ROBOT: 'ROBOT',
}

export const ANIMATION = {
  ROBOT_IDLE: 'ROBOT_IDLE',
  ROBOT_WALK: 'ROBOT_WALK',
  ROBOT_AXE_WALK: 'ROBOT_AXE_WALK',
  ROBOT_AXE_SLASH: 'ROBOT_AXE_SLASH',
  ROBOT_BASKET_WALK: 'ROBOT_BASKET_WALK',
  ROBOT_BASKET_THRUST: 'ROBOT_BASKET_THRUST',
  ROBOT_BASKET_WOODS_WALK: 'ROBOT_BASKET_WOODS_WALK',
  ROBOT_BASKET_WATER_WALK: 'ROBOT_BASKET_WATER_WALK',
}
